<?php
require_once __DIR__ . '/includes/db.php';
require_once __DIR__ . '/includes/auth.php';
requireLogin();
$id = (int)($_GET['id'] ?? 0);
$user = currentUser();
$stmt = $pdo->prepare('SELECT p.*, u.name AS owner_name, u.email AS owner_email FROM projects p JOIN users u ON p.user_id = u.id WHERE p.id = ? AND p.user_id = ?');
$stmt->execute([$id, $user['id']]);
$project = $stmt->fetch();
if (!$project) die('Report not found');
$report = json_decode($project['ai_report_json'], true) ?: [];
$best = $report['best_idea'] ?? [];
$costs = $report['costs'] ?? [];
$income = $report['income'] ?? [];
$roi = $report['roi'] ?? [];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><title>LandVision AI Premium Report</title>
<style>
body{font-family:Arial,sans-serif;color:#10233f;margin:0;background:#eef3f7}.btns{max-width:1050px;margin:20px auto;text-align:right}.btn{background:#08795b;color:#fff;border:0;border-radius:10px;padding:12px 18px;cursor:pointer}.report{max-width:1050px;margin:0 auto 30px;background:#fff;padding:38px;border-radius:22px;box-shadow:0 20px 60px rgba(16,35,63,.12)}.top{display:flex;justify-content:space-between;gap:20px;border-bottom:4px solid #08795b;padding-bottom:18px}.brand{font-size:28px;font-weight:900;color:#08795b}.muted{color:#667085}.section{margin-top:28px;break-inside:avoid}.hero{display:grid;grid-template-columns:1.1fr 1fr;gap:20px}.image{width:100%;height:280px;object-fit:cover;border-radius:18px}.box{border:1px solid #d8e2ec;border-radius:16px;padding:18px;background:#fbfdff}h1{font-size:36px;margin:10px 0}h2{margin:0 0 12px;font-size:22px}h3{margin:0 0 8px}.badge{display:inline-block;padding:6px 12px;border-radius:99px;background:#e6fff5;color:#08795b;font-weight:800;font-size:12px}.stats,.scores,.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.scores{grid-template-columns:repeat(5,1fr)}.stats div,.scores div{border:1px solid #d8e2ec;border-radius:14px;padding:14px;background:#fff}.stats span,.scores span{display:block;color:#667085;font-size:12px}.stats strong,.scores strong{font-size:22px;color:#10233f}table{width:100%;border-collapse:collapse}th,td{padding:11px;border-bottom:1px solid #e5edf5;text-align:left;vertical-align:top}th{background:#f1fbf7;color:#08795b}.flow{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.flow div{background:#e6fff5;border:1px solid #a7efcf;border-radius:14px;padding:12px 14px;font-weight:800}.risk{display:grid;grid-template-columns:1fr 2fr;gap:10px;margin:10px 0;padding:12px;border:1px solid #e5edf5;border-radius:14px}.final{background:linear-gradient(135deg,#053f37,#0a946b);color:#fff}.final h2,.final p{color:#fff}.legal{font-size:12px;color:#667085}@media print{body{background:#fff}.btns{display:none}.report{box-shadow:none;border-radius:0;margin:0;max-width:100%;padding:18px}.section{break-inside:avoid}.hero{grid-template-columns:1fr}.scores{grid-template-columns:repeat(3,1fr)}}
</style></head><body>
<div class="btns"><button class="btn" onclick="window.print()">Print / Save as PDF</button></div>
<div class="report">
    <div class="top"><div><div class="brand">LandVision AI</div><p class="muted">Premium Land Feasibility & Business Decision Report</p></div><div><b>Generated:</b> <?= e($report['generated_at'] ?? date('Y-m-d')) ?><br><b>Owner:</b> <?= e($project['owner_name']) ?><br><b>Email:</b> <?= e($project['owner_email']) ?></div></div>
    <div class="section hero"><div><?php if ($project['image_path']): ?><img class="image" src="<?= e($project['image_path']) ?>" alt="Land image"><?php endif; ?></div><div class="box"><span class="badge">Recommended Business</span><h1><?= e($best['name'] ?? '') ?></h1><p><?= e($report['summary'] ?? '') ?></p><div class="stats"><div><span>Budget</span><strong><?= money($project['budget']) ?></strong></div><div><span>AI Score</span><strong><?= e($best['score'] ?? '-') ?></strong></div><div><span>Net Profit</span><strong><?= money($roi['estimated_net_profit'] ?? 0) ?></strong></div><div><span>Payback</span><strong><?= e($roi['payback_period_months'] ?? '-') ?> mo</strong></div></div></div></div>
    <div class="section grid"><div class="box"><b>District</b><br><?= e($project['district']) ?></div><div class="box"><b>Land Size</b><br><?= e($project['land_size_perches']) ?> perches</div><div class="box"><b>Land Type</b><br><?= e(ucwords(str_replace('_',' ', $project['land_type']))) ?></div><div class="box"><b>Target Customers</b><br><?= e($project['target_customer']) ?></div></div>
    <div class="section"><h2>Executive Summary</h2><div class="box"><ul><?php foreach (($best['reasons'] ?? []) as $r): ?><li><?= e($r) ?></li><?php endforeach; ?></ul></div></div>
    <div class="section"><h2>Land Potential Score</h2><div class="scores"><?php foreach(($report['potential_scores'] ?? []) as $s): ?><div><span><?= e($s['label']) ?></span><strong><?= e($s['score']) ?>/100</strong><br><span><?= e($s['level']) ?></span></div><?php endforeach; ?></div></div>
    <div class="section"><h2>Scenario Comparison</h2><table><tr><th>Plan</th><th>Investment</th><th>Monthly Profit</th><th>Risk</th><th>Best For</th></tr><?php foreach(($report['scenario_comparison'] ?? []) as $sc): ?><tr><td><?= e($sc['plan']) ?></td><td><?= money($sc['investment']) ?></td><td><?= money($sc['monthly_profit']) ?></td><td><?= e($sc['risk']) ?></td><td><?= e($sc['best_for']) ?></td></tr><?php endforeach; ?></table></div>
    <div class="section"><h2>Business Comparison</h2><table><tr><th>Idea</th><th>Cost</th><th>Income</th><th>Risk</th><th>Decision</th></tr><?php foreach(($report['business_comparison'] ?? []) as $r): ?><tr><td><?= e($r['idea']) ?></td><td><?= e($r['cost_level']) ?></td><td><?= e($r['income_potential']) ?></td><td><?= e($r['risk_level']) ?></td><td><?= e($r['recommendation']) ?></td></tr><?php endforeach; ?></table></div>
    <div class="section"><h2>Financial Plan</h2><div class="grid"><div class="box"><b>Monthly Revenue:</b><br><?= money($income['monthly_revenue_low'] ?? 0) ?> - <?= money($income['monthly_revenue_high'] ?? 0) ?><br><br><b>Monthly Expenses:</b><br><?= money($roi['estimated_monthly_expenses'] ?? 0) ?><br><br><b>Net Profit:</b><br><?= money($roi['estimated_net_profit'] ?? 0) ?><br><br><b>Payback:</b><br><?= e($roi['payback_period_months'] ?? '-') ?> months</div><div class="box"><b>Income Streams</b><ul><?php foreach (($income['income_streams'] ?? []) as $stream): ?><li><?= e($stream) ?></li><?php endforeach; ?></ul><p><?= e($report['break_even']['summary'] ?? '') ?></p></div></div></div>
    <div class="section"><h2>Cost Estimate</h2><table><tr><th>Item</th><th>Estimated Cost</th></tr><?php foreach (($costs['items'] ?? []) as $item): ?><tr><td><?= e($item['item']) ?></td><td><?= money($item['cost']) ?></td></tr><?php endforeach; ?><tr><th>Total</th><th><?= money($costs['estimated_total'] ?? 0) ?></th></tr><tr><th>Budget Gap</th><th><?= money($costs['budget_gap'] ?? 0) ?></th></tr></table><p><b><?= e($costs['budget_status'] ?? '') ?>:</b> <?= e($costs['note'] ?? '') ?></p></div>
    <div class="section"><h2>Visual Master Plan</h2><div class="flow"><?php foreach (($report['layout_diagram'] ?? []) as $step): ?><div><?= e($step) ?></div><?php endforeach; ?></div></div>
    <div class="section"><h2>Risk + Solution</h2><?php foreach (($report['risks'] ?? []) as $risk): ?><div class="risk"><strong><?= e($risk['risk']) ?></strong><span><?= e($risk['solution']) ?></span></div><?php endforeach; ?></div>
    <div class="section"><h2>SWOT Analysis</h2><div class="grid"><?php foreach(['strengths'=>'Strengths','weaknesses'=>'Weaknesses','opportunities'=>'Opportunities','threats'=>'Threats'] as $k=>$label): ?><div class="box"><h3><?= e($label) ?></h3><ul><?php foreach (($report['swot'][$k] ?? []) as $i): ?><li><?= e($i) ?></li><?php endforeach; ?></ul></div><?php endforeach; ?></div></div>
    <div class="section grid"><div class="box"><h2>Development Phases</h2><ul><?php foreach (($report['phases'] ?? []) as $p): ?><li><b><?= e($p['phase']) ?>:</b> <?= e($p['work']) ?></li><?php endforeach; ?></ul></div><div class="box"><h2>Marketing Plan</h2><ul><?php foreach (($report['marketing'] ?? []) as $m): ?><li><?= e($m) ?></li><?php endforeach; ?></ul></div></div>
    <div class="section box final"><h2>Final Recommendation</h2><p><?= e($report['final_advice'] ?? '') ?></p></div>
</div></body></html>
